# Numpy Part 1

## Tugas 1: Persiapan Data
- Import library NumPy
- Buat sebuah NumPy array dengan data berikut: [25, -10, 0, -5, 40, 15].
- Simpan array tersebut ke dalam variabel bernama nilai_ujian.
- Cetak variabel nilai_ujian untuk memastikan data sudah benar


In [5]:
import numpy

nilai_ujian = numpy.array([25, -10, 0, -5, 40, 15])
nilai_ujian

array([ 25, -10,   0,  -5,  40,  15])

## Tugas 2: Analisis Statistik Dasar
<br>Gunakan variabel `nilai_ujian` yang sudah dibuat untuk melakukan analisis berikut:
- Hitung nilai rata-rata (mean) dari semua elemen dan simpan ke variabel `rata_rata`.
- Temukan nilai tertinggi (max) dari semua elemen dan simpan ke variabel `nilai_tertinggi`.
- Cetak kedua hasil tersebut dengan format yang jelas.

In [6]:
rata_rata = numpy.average(nilai_ujian)
nilai_tertinggi = numpy.max(nilai_ujian)

print(rata_rata)
print(nilai_tertinggi)

10.833333333333334
40


## Tugas 3: Transformasi Nilai
- Buat array baru bernama `nilai_absolut` yang berisi nilai mutlak (absolute) dari setiap elemen di `nilai_ujian`.
- Buat array baru bernama `penanda_nilai` yang menunjukkan penanda (sign) dari setiap elemen (-1 untuk negatif, 0 untuk nol, 1 untuk positif).
- Cetak kedua array baru tersebut.

In [19]:
nilai_absolut = numpy.absolute(nilai_ujian)
display(nilai_absolut)

array([25, 10,  0,  5, 40, 15])

## Tugas 4: Pengurutan Data
- Gunakan fungsi `np.sort()` untuk membuat array baru yang sudah terurut dari `nilai_ujian`. Simpan ke variabel `nilai_terurut`.
- Cetak `nilai_terurut`.
- Cetak juga nilai_ujian yang asli untuk membuktikan bahwa array aslinya tidak berubah.

In [23]:
nilai_terurut = numpy.sort(nilai_ujian)

display(nilai_terurut)
display(nilai_ujian)
# bisa juga pakai ic() untuk print

array([-10,  -5,   0,  15,  25,  40])

array([ 25, -10,   0,  -5,  40,  15])

# NumPy Part 2

## Tugas 1: Persiapan Data Awal
- Import `library NumPy` dengan alias `np`.
- Buat tiga buah array seperti di bawah ini:
- `array_a`: Berisi nilai [5, 10, 15, 20, 25, 30]
- `array_b`: Berisi nilai [2, 4, 6, 8, 10, 12]
- `matriks_c`: Sebuah matriks 2x3 dengan data [[1, 2, 3], [4, 5, 6]]
- Cetak ketiga variabel tersebut untuk memastikan data sudah benar.

In [9]:
import numpy as np

array_a = np.array([5, 10, 15, 20, 25, 30])
array_b = np.array([2, 4, 6, 8, 10, 12])
matriks_c = np.array([[1, 2, 3], [4, 5, 6]])

print(array_a)
print(array_b)
print(matriks_c)

[ 5 10 15 20 25 30]
[ 2  4  6  8 10 12]
[[1 2 3]
 [4 5 6]]


## Tugas 2: Menggabungkan dan Menumpuk Array
- Gunakan `np.concatenate()` untuk menggabungkan `array_a` dan `array_b` menjadi satu array 1D.
- Gunakan `np.vstack()` (vertical stack) untuk menumpuk `array_a` dan `array_b` secara vertikal, menghasilkan sebuah matriks 2D

In [13]:
array_1D = np.concatenate((array_a, array_b))
matriks_2D = np.vstack((array_a, array_b))

print(array_1D)
print(matriks_2D)

[ 5 10 15 20 25 30  2  4  6  8 10 12]
[[ 5 10 15 20 25 30]
 [ 2  4  6  8 10 12]]


## Tugas 3: Memisahkan Array
- Gunakan `np.split()` untuk memisahkan `array_a` menjadi 3 bagian yang sama besar.
- Buat array baru array_panjang dari 0-9.
Gunakan `np.split()` untuk memisahkan `array_panjang` pada indeks ke-3 dan ke-7.

In [68]:
np.split(array_a, 3)

array_panjang = np.arange(0,10)

# arr.shape() -> ukuran array
# arr.ndin() -> melihat dimensi array
# arr.size() -> total elemen dari array
# arr.dtype() -> data type
# arr.flatten() -> akan diubah jadi array satu dimensi
# arr.reshape() -> mengubah ukuran array
# arr.astype() -> mengubah tipe data array
# np.full()

## Tugas 4: Operasi Aritmatika Dasar (Element-Wise)

- Lakukan penjumlahan, perkalian, dan pembagian antara `array_a` dan `array_b`.
- Lakukan operasi pangkat pada `array_b` dengan 2.

In [28]:
print(array_a + array_b)
print(array_a * array_b)
print(array_a / array_b)
print(array_b **2)

[ 7 14 21 28 35 42]
[ 10  40  90 160 250 360]
[2.5 2.5 2.5 2.5 2.5 2.5]
[  4  16  36  64 100 144]


## Tugas 5: Fungsi Matematika Element-Wise

- Hitung akar kuadrat (square root) dari `array_a`.
- Hitung nilai sinus dari setiap elemen di `matriks_c`.
- Buat array baru dengan nilai desimal, lalu bulatkan nilainya menggunakan `np.round()`.

In [31]:
print(array_a **0.5)
print(np.sin(matriks_c))

[2.23606798 3.16227766 3.87298335 4.47213595 5.         5.47722558]
[[ 0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155 ]]


## Tugas 6: Operasi Perbandingan (Element-Wise)
- Bandingkan `array_a` dan `array_b` untuk mencari tahu elemen mana di `array_a` yang lebih besar.
- Cari semua nilai di `array_a` yang lebih besar dari 18 dan tampilkan nilainya.

## Tugas 7: Operasi Matriks (Perkalian Matriks)

- Buat matriks baru `matriks_d` berukuran 3x2.
- Lakukan perkalian matriks antara `matriks_c` (2x3) dan `matriks_d` (3x2) menggunakan operator @.
- Lakukan operasi yang sama menggunakan `np.dot()` untuk perbandingan.

## Tugas 8: Operasi In-place (Modifikasi Langsung)

- Buat salinan `array_a` menggunakan `.copy()` agar tidak mengubah data asli kita.
- Gunakan operator += untuk menambahkan 5 ke setiap elemen di array salinan tersebut.
- Cetak array salinan dan array asli untuk melihat perbedaannya.

In [35]:
array_baru = array_a.copy()
array_baru += 5

display(array_baru)

array([10, 15, 20, 25, 30, 35])

# Pandas

## Tugas 1: Membaca CSV dan Menampilkan Informasi Dasar

**Instruksi:**
1. Baca file bernama `data_hands-on_2.csv` ke dalam DataFrame bernama `df`.
2. Tampilkan 5 baris pertama dengan `df.head()`.
3. Tampilkan informasi ringkas dataset menggunakan `df.info()`.

**Expected Output (contoh ringkas):**

```
   Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0           0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1           0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2           0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3           0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4           0.0     1.0       1.0        1.0  24.0     0.0     0.0   
```

```
<class 'pandas.core.frame.DataFrame'>
RangeIndex: ... entries, 0 to ...
Data columns (total 22 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Diabetes_012          ... non-null    float64
 1   HighBP                ... non-null    float64
 ...
21   Income                ... non-null    float64
dtypes: float64(...), int64(...), object(...)
memory usage: ...
```

In [38]:
# Write your code here
import pandas as pd

df = pd.read_csv('data_hands-on_2.csv')
display(df.head())
display(df.info())

Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
0           0.0     1.0       1.0        1.0  40.0     1.0     0.0   
1           0.0     0.0       0.0        0.0  25.0     1.0     0.0   
2           0.0     1.0       1.0        1.0  28.0     0.0     0.0   
3           0.0     1.0       0.0        1.0  27.0     0.0     0.0   
4           0.0     1.0       1.0        1.0  24.0     0.0     0.0   

   HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
0                   0.0           0.0     0.0  ...            1.0   
1                   0.0           1.0     0.0  ...            0.0   
2                   0.0           0.0     1.0  ...            1.0   
3                   0.0           1.0     1.0  ...            1.0   
4                   0.0           1.0     1.0  ...            1.0   

   NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  Education  \
0          0.0      5.0      18.0      15.0       1.0  0.0   9.0        4.0   
1          1.0      3.0       0.0       0.0       0.0  0.0   7.0        6.0   
2          1.0      5.0      30.0      30.0       1.0  0.0   9.0        4.0   
3          0.0      2.0       0.0       0.0       0.0  0.0  11.0        3.0   
4          0.0      2.0       3.0       0.0       0.0  0.0  11.0        5.0   

   Income  
0     3.0  
1     1.0  
2     8.0  
3     6.0  
4     4.0  

[5 rows x 22 columns]

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 253680 entries, 0 to 253679
Data columns (total 22 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   Diabetes_012          253680 non-null  float64
 1   HighBP                253680 non-null  float64
 2   HighChol              253680 non-null  float64
 3   CholCheck             253680 non-null  float64
 4   BMI                   253680 non-null  float64
 5   Smoker                253680 non-null  float64
 6   Stroke                253680 non-null  float64
 7   HeartDiseaseorAttack  253680 non-null  float64
 8   PhysActivity          253680 non-null  float64
 9   Fruits                253680 non-null  float64
 10  Veggies               253680 non-null  float64
 11  HvyAlcoholConsump     253680 non-null  float64
 12  AnyHealthcare         253680 non-null  float64
 13  NoDocbcCost           253680 non-null  float64
 14  GenHlth               253680 non-null  float64
 15  

None

## Tugas 2: Eksplorasi Statistik Deskriptif

**Instruksi:**
1. Jalankan `df.describe()` untuk melihat ringkasan default.
2. Coba tampilkan ringkasan **hanya untuk kolom object**.
  - Jika error, maka artinya tidak ada column object, bisa dilewati saja  
  - (Opsional) Bisa gunakan error handling untuk handle ketika tidak ada kolom object, tampilkan pesan `"Tidak ada kolom object dalam dataset."`.
3. Jalankan `df.describe(include=['number'])` untuk ringkasan numerik.
4. Ubah persentil yang ditampilkan menjadi **5%, 50%, dan 95%**.

**Expected Output (contoh ringkas):**
- Default: ringkasan statistik semua kolom numerik.  
- Object: `"Tidak ada kolom object dalam dataset."`  
- Numeric: ringkasan numerik sama dengan default.  
- Custom percentiles: statistik dengan 5%, 50%, 95%.

In [42]:
# Write your code here
df.describe()

Diabetes_012         HighBP       HighChol      CholCheck  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        0.296921       0.429001       0.424121       0.962670   
std         0.698160       0.494934       0.494210       0.189571   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000       0.000000       0.000000       1.000000   
50%         0.000000       0.000000       0.000000       1.000000   
75%         0.000000       1.000000       1.000000       1.000000   
max         2.000000       1.000000       1.000000       1.000000   

                 BMI         Smoker         Stroke  HeartDiseaseorAttack  \
count  253680.000000  253680.000000  253680.000000         253680.000000   
mean       28.382364       0.443169       0.040571              0.094186   
std         6.608694       0.496761       0.197294              0.292087   
min        12.000000       0.000000       0.000000              0.000000   
25%        24.000000       0.000000       0.000000              0.000000   
50%        27.000000       0.000000       0.000000              0.000000   
75%        31.000000       1.000000       0.000000              0.000000   
max        98.000000       1.000000       1.000000              1.000000   

        PhysActivity         Fruits  ...  AnyHealthcare    NoDocbcCost  \
count  253680.000000  253680.000000  ...  253680.000000  253680.000000   
mean        0.756544       0.634256  ...       0.951053       0.084177   
std         0.429169       0.481639  ...       0.215759       0.277654   
min         0.000000       0.000000  ...       0.000000       0.000000   
25%         1.000000       0.000000  ...       1.000000       0.000000   
50%         1.000000       1.000000  ...       1.000000       0.000000   
75%         1.000000       1.000000  ...       1.000000       0.000000   
max         1.000000       1.000000  ...       1.000000       1.000000   

             GenHlth       MentHlth       PhysHlth       DiffWalk  \
count  253680.000000  253680.000000  253680.000000  253680.000000   
mean        2.511392       3.184772       4.242081       0.168224   
std         1.068477       7.412847       8.717951       0.374066   
min         1.000000       0.000000       0.000000       0.000000   
25%         2.000000       0.000000       0.000000       0.000000   
50%         2.000000       0.000000       0.000000       0.000000   
75%         3.000000       2.000000       3.000000       0.000000   
max         5.000000      30.000000      30.000000       1.000000   

                 Sex            Age      Education         Income  
count  253680.000000  253680.000000  253680.000000  253680.000000  
mean        0.440342       8.032119       5.050434       6.053875  
std         0.496429       3.054220       0.985774       2.071148  
min         0.000000       1.000000       1.000000       1.000000  
25%         0.000000       6.000000       4.000000       5.000000  
50%         0.000000       8.000000       5.000000       7.000000  
75%         1.000000      10.000000       6.000000       8.000000  
max         1.000000      13.000000       6.000000       8.000000  

[8 rows x 22 columns]

## Tugas 3: Mengecek Shape, Size, dan Mengambil Sampel

**Instruksi:**
1. Gunakan atribut `df.shape` untuk menampilkan jumlah baris dan kolom.
2. Gunakan atribut `df.size` untuk menampilkan jumlah total elemen (baris × kolom).
3. Ambil 5 baris acak dari dataset menggunakan `df.sample(5)`.
4. Ambil 3 baris acak dari dataset, tetapi gunakan parameter `random_state=42` agar hasilnya konsisten.

**Expected Output (contoh ringkas):**
- Shape: `(253680, 22)`
- Size: `5580960`
- Sample 5 rows: (5 baris acak)
- Sample 3 rows dengan seed: (3 baris acak, selalu sama tiap dijalankan)

In [57]:
# Write your code here
display(df.shape)
display(df.size)

display(df.sample(5))
display(df.sample(3, random_state=42))

(253680, 22)

5580960

Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
120903           0.0     0.0       0.0        1.0  37.0     0.0     0.0   
18114            2.0     1.0       0.0        1.0  29.0     1.0     0.0   
86506            0.0     1.0       1.0        1.0  26.0     0.0     0.0   
72960            0.0     1.0       1.0        1.0  27.0     1.0     0.0   
108609           0.0     0.0       1.0        1.0  23.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
120903                   0.0           0.0     0.0  ...            0.0   
18114                    0.0           0.0     1.0  ...            1.0   
86506                    1.0           1.0     1.0  ...            1.0   
72960                    1.0           1.0     1.0  ...            1.0   
108609                   0.0           1.0     0.0  ...            1.0   

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
120903          1.0      4.0      30.0      10.0       0.0  0.0   2.0   
18114           0.0      5.0       0.0      30.0       0.0  1.0   9.0   
86506           1.0      2.0       0.0      14.0       0.0  1.0  10.0   
72960           0.0      3.0       0.0       0.0       0.0  0.0  10.0   
108609          0.0      3.0       0.0       0.0       0.0  0.0  10.0   

        Education  Income  
120903        4.0     5.0  
18114         5.0     2.0  
86506         6.0     8.0  
72960         5.0     5.0  
108609        6.0     2.0  

[5 rows x 22 columns]

Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  \
219620           0.0     0.0       0.0        1.0  21.0     0.0     0.0   
132821           0.0     1.0       1.0        1.0  28.0     0.0     0.0   
151862           0.0     0.0       0.0        1.0  24.0     0.0     0.0   

        HeartDiseaseorAttack  PhysActivity  Fruits  ...  AnyHealthcare  \
219620                   0.0           0.0     1.0  ...            1.0   
132821                   0.0           1.0     1.0  ...            1.0   
151862                   0.0           1.0     1.0  ...            1.0   

        NoDocbcCost  GenHlth  MentHlth  PhysHlth  DiffWalk  Sex   Age  \
219620          0.0      3.0       3.0       7.0       0.0  0.0   7.0   
132821          0.0      3.0       0.0       0.0       0.0  0.0  13.0   
151862          0.0      1.0       0.0       0.0       0.0  1.0   1.0   

        Education  Income  
219620        4.0     2.0  
132821        6.0     6.0  
151862        4.0     7.0  

[3 rows x 22 columns]

## Tugas 4: Seleksi Data dengan `.loc` dan `.iloc`


**Instruksi:**
1. Pilih baris ke-0 sampai ke-4 dan kolom `['Diabetes_012', 'BMI', 'Age']` menggunakan `.loc`, simpan ke dalam `df_loc`.
2. Pilih baris ke-10 sampai ke-14 dan kolom ke-0 sampai ke-2 menggunakan `.iloc`, simpan ke dalam `df_iloc`.
3. Tampilkan kedua DataFrame (`df_loc` dan `df_iloc`) untuk melihat hasilnya.

**Expected Output (contoh ringkas):**

👉 `df_loc`
```
    Diabetes_012  BMI   Age
0   0.0           40.0  9.0
1   0.0           25.0  7.0
2   0.0           8.0   9.0
3   0.0           27.0  11.0
4   0.0           24.0  11.0
```

👉 `df_iloc`
```
    Diabetes_012  HighBP  HighChol
10  0.0           0.0     0.0
11  0.0           0.0     0.0
12  0.0           0.0     0.0
13  0.0           0.0     0.0
14  0.0           0.0     1.0
```

In [61]:
# Write your code here


## Tugas 5: Filtering Data

**Instruksi:**
1. Pilih semua baris dengan **BMI lebih dari 30** dan simpan ke dalam `df_obese`.
2. Pilih semua baris dengan **Diabetes_012 = 1** dan simpan ke dalam `df_diabetes`.
3. Terapkan filter gabungan: pilih semua baris dengan **BMI > 30** dan **Diabetes_012 = 1**, simpan ke dalam `df_highrisk`.
4. Tampilkan jumlah baris untuk tiap DataFrame hasil filter (`len(df_xxx)`).

**Expected Output (contoh ringkas):**
- `df_obese` → DataFrame dengan hanya baris BMI > 30  
- `df_diabetes` → DataFrame dengan hanya baris Diabetes_012 = 1  
- `df_highrisk` → DataFrame gabungan kondisi  
- Output jumlah baris, misalnya:  
  - Jumlah baris df_obese: 98000
  - Jumlah baris df_diabetes: 34000
  - Jumlah baris df_highrisk: 12000

In [77]:
# Write your code here
df_obese = df[df.BMI > 30]
df_diabetes = df[df.Diabetes_012 == 1]

## Tugas 6: Filtering dengan `.isin()`

**Instruksi:**
1. Pilih semua baris di mana kolom `Age` bernilai **[7, 8, 9]**, simpan ke dalam `df_agegroup`.
2. Pilih semua baris di mana kolom `Income` bernilai **[1, 2]** (pendapatan rendah), simpan ke dalam `df_lowincome`.
3. Tampilkan 5 baris pertama dari masing-masing DataFrame.

**Expected Output (contoh ringkas):**

👉 `df_agegroup`
```
    Diabetes_012  HighBP  HighChol  ... Age   Education Income
1   0.0           0.0     0.0       ... 7.0   6.0       1.0
2   0.0           1.0     1.0       ... 9.0   4.0       8.0
...
```


👉 `df_lowincome`
```
    Diabetes_012  HighBP  HighChol  ... Age   Education Income
1   0.0           0.0     0.0       ... 7.0   6.0       1.0
8   0.0           1.0     1.0       ... 11.0  4.0       2.0
...
```

In [ ]:
# Write your code here

## Tugas 7: Menghapus Kolom, Menyimpan Kolom Tertentu, dan Membuat Fitur Baru

**Instruksi:**
1. **Drop kolom** `['CholCheck', 'Smoker']` dari `df`, simpan hasilnya ke `df_drop`.
2. **Keep kolom** `['Diabetes_012', 'BMI', 'Age', 'HighBP', 'HighChol']` dari `df`, simpan ke `df_keep`.
3. Pada `df_keep`, buat kolom fitur baru bernama **`BMI_Category`**:
   - `Underweight` jika BMI < 18.5  
   - `Normal` jika 18.5 ≤ BMI < 25  
   - `Overweight` jika 25 ≤ BMI < 30  
   - `Obese` jika BMI ≥ 30
4. Tampilkan `df_drop.head()` dan `df_keep.head()`.

**Catatan:**
- Gunakan `.copy()` saat membuat subset untuk menghindari `SettingWithCopyWarning`.
- Gunakan `pd.cut` untuk membuat kategori BMI.

**Expected Output (contoh ringkas):**

👉 `df_drop.head()` (tanpa kolom `CholCheck`, `Smoker`)
```
    Diabetes_012  HighBP  HighChol  BMI   Stroke    HeartDiseaseorAttack  ...
0   0.0           1.0     1.0       40.0  0.0       0.0                   ...
1   0.0           0.0     0.0       25.0  0.0       0.0                   ...
...
```


👉 `df_keep.head()` (dengan kolom baru `BMI_Category`)
```
    Diabetes_012  BMI   Age   HighBP  HighChol  BMI_Category
0   0.0           40.0  9.0   1.0     1.0       Obese
1   0.0           25.0  7.0   0.0     0.0       Overweight
2   0.0           28.0  9.0   1.0     1.0       Overweight
3   0.0           27.0  11.0  1.0     0.0       Overweight
4   0.0           24.0  11.0  1.0     1.0       Normal
...
```

In [ ]:
# Write your code here

## Tugas 8: Buat Fitur dari Operasi Aritmetika, Hapus Kolom Asal, dan Rename

**Instruksi:**
1. Buat salinan kerja: `df_fe = df.copy()`.
2. Buat kolom baru **sementara** bernama `UnhealthyDays_temp` = `PhysHlth` + `MentHlth`.
3. Hapus kolom asal `['PhysHlth', 'MentHlth']` dari `df_fe`.
4. Rename `UnhealthyDays_temp` menjadi **`UnhealthyDays`**.
5. Tampilkan `df_fe[['UnhealthyDays']].head()` dan pastikan kolom `PhysHlth` dan `MentHlth` **sudah tidak ada** (contoh: tampilkan daftar kolom).

**Expected Output (contoh ringkas):**
- Preview kolom baru:
```
    UnhealthyDays
0   33.0
1   0.0
2   60.0
3   0.0
4   3.0
```
- Daftar kolom **tidak** mengandung `PhysHlth` & `MentHlth`, dan **mengandung** `UnhealthyDays`.
```
['Diabetes_012', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker', ..., 'DiffWalk', 'Sex', 'Age', 'Education', 'Income', 'UnhealthyDays']
```


In [ ]:
# Write your code here

## Tugas 9: Menggabungkan DataFrame dengan `pd.concat()` dan `pd.merge()`

### 9.a — pd.concat (baris/row-wise): menumpuk dua DataFrame

Instruksi:
1. Buat dua DataFrame baru, df_part1 dan df_part2, dengan mengambil 5 baris pertama dan 5 baris berikutnya dari df.
2. Gabungkan keduanya menjadi DataFrame baru df_concat_rows menggunakan pd.concat() dengan orientasi baris.
3. Tampilkan 10 baris hasil gabungan.

---

Expected Output (contoh ringkas):
```
   Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  ...
0          0.0      1.0       1.0        1.0  40.0     1.0     0.0  ...
1          0.0      0.0       0.0        0.0  25.0     1.0     0.0  ...
...
9          0.0      1.0       1.0        1.0  23.0     0.0     0.0  ...
```

In [ ]:
# Write your code here

### 9.b — pd.concat (kolom/column-wise): menyatukan fitur berdasar index

Instruksi:
1. Ambil 5 baris pertama dataset df menjadi df_cols1 dengan hanya kolom: ['Diabetes_012', 'HighBP', 'HighChol'].
2. Ambil 5 baris pertama dataset df menjadi df_cols2 dengan kolom: ['BMI', 'Smoker', 'Stroke'].
3. Gabungkan kedua DataFrame ini berdampingan menggunakan pd.concat() dengan orientasi kolom.
4. Tampilkan hasil gabungan.

---

Expected Output (contoh ringkas):
```
   Diabetes_012  HighBP  HighChol   BMI  Smoker  Stroke
0          0.0      1.0       1.0  40.0     1.0     0.0
1          0.0      0.0       0.0  25.0     1.0     0.0
...
4          0.0      1.0       1.0  24.0     0.0     0.0
```

In [ ]:
# Write your code here

### 9.c Menggabungkan DataFrame dengan pd.merge() (Inner Join)

Instruksi:
1. Ambil 10 baris pertama dataset df menjadi df_left dan df_right.
2. Pada df_left, ambil hanya kolom ['Age', 'Education', 'Income'].
3. Pada df_right, ambil kolom ['Age', 'BMI', 'Smoker'].
4. Gabungkan kedua DataFrame tersebut berdasarkan kolom Age menggunakan pd.merge() dengan metode inner.
5. Tampilkan hasil gabungan.

---

Expected Output (contoh ringkas):
```
   Age  Education  Income   BMI  Smoker
0   9.0        4.0     3.0  40.0     1.0
1   7.0        6.0     1.0  25.0     1.0
...
```

In [ ]:
# Write your code here

### 9.d Perbedaan Jenis Join pada pd.merge()

Instruksi:
1. Gunakan df_left dan df_right dari 9.c.
2. Lakukan empat jenis penggabungan:
    - Inner Join → hanya data dengan Age yang cocok.
    - Left Join → semua baris dari df_left.
    - Right Join → semua baris dari df_right.
    - Outer Join → semua data dari kedua tabel.
3. Tampilkan hasil setiap join.

---

Expected Output (contoh ringkas Inner vs Outer):
```
# Inner Join
   Age  Education  Income   BMI  Smoker
0   9.0        4.0     3.0  40.0     1.0

# Outer Join
   Age  Education  Income   BMI  Smoker
0   9.0        4.0     3.0  40.0     1.0
1   11.0       3.0     6.0   NaN     NaN
...
```

In [ ]:
# Write your code here

## Tugas 10: Menangani Missing Values (NaN)

**Persiapan Dataset**

Instruksi:

- Jalankan sel ini untuk membuat beberapa nilai NaN secara sengaja di dataset.
Tidak ada output yang diharapkan pada tahap ini — ini hanya menyiapkan dataset untuk tugas berikutnya.

In [ ]:
# Jalankan sel ini untuk membuat beberapa nilai NaN
df_nan = df.copy()

# Membuat beberapa NaN secara acak
df_nan.loc[5:10, 'BMI'] = None
df_nan.loc[3:8, 'Smoker'] = None
df_nan.loc[0:2, 'Income'] = None

print("Dataset telah dimodifikasi: beberapa nilai NaN ditambahkan.")

### 10.a Cek Jumlah Missing Values per Kolom

Instruksi:
1. Gunakan fungsi isna() atau isnull() untuk memeriksa nilai yang hilang.
2. Hitung jumlah missing values per kolom menggunakan sum().
3. Simpan hasilnya ke dalam DataFrame bernama missing_count dan tampilkan.

Expected Output (contoh ringkas):
```
      missing_count
BMI             6
Smoker          6
Income          3
...           ...
```

In [ ]:
# Write your code here

### 10.b Menghapus Baris dengan Missing Values

Instruksi:
1. Hapus semua baris yang memiliki minimal satu nilai NaN menggunakan dropna().
2. Simpan hasilnya ke dalam DataFrame baru bernama df_dropna.
3. Tampilkan 5 baris pertama dari df_dropna.

Expected Output (contoh ringkas):
```
   Diabetes_012  HighBP  HighChol  CholCheck   BMI  Smoker  Stroke  ...
0          0.0      1.0       1.0        1.0  40.0     1.0     0.0 ...
1          0.0      0.0       0.0        0.0  25.0     1.0     0.0 ...
...
```

In [ ]:
# Write your code here

### 10.c Mengisi Missing Values dengan Nilai Tertentu

Instruksi:
1. Salin df ke DataFrame baru bernama df_fillna.
2. Isi missing values pada kolom BMI dengan rata-rata (mean).
3. Isi missing values pada kolom Smoker dengan modus (nilai yang paling sering muncul).
4. Tampilkan 5 baris pertama dari df_fillna.

Expected Output (contoh ringkas):
```
   BMI  Smoker
0  40.0    1.0
1  25.0    1.0
2  28.0    0.0
3  27.0    0.0
4  24.0    0.0
```


In [ ]:
# Write your code here

### 10.d Mengisi Missing Values dengan Forward Fill & Backward Fill

Instruksi:
1. Salin df ke DataFrame baru bernama df_forward, lalu lakukan forward fill pada kolom Income untuk mengisi nilai NaN dengan nilai baris sebelumnya.
2. Salin df ke DataFrame baru bernama df_backward, lalu lakukan backward fill pada kolom Income untuk mengisi nilai NaN dengan nilai baris sesudahnya.
3. Tampilkan hasil dari df_forward dan df_backward.

Expected Output (contoh ringkas):
```
# Forward fill
0    3.0
1    3.0
2    3.0

# Backward fill
0    1.0
1    1.0
2    8.0
```

In [ ]:
# Write your code here

## Tugas 11: GroupBy dan Agregasi

### 11.a GroupBy Satu Kolom dengan Agregasi Tunggal

**Instruksi:**  
1. Gunakan `groupby()` untuk mengelompokkan data berdasarkan kolom `Sex`.  
2. Hitung **rata-rata** (`mean`) dari kolom `BMI` untuk setiap grup.  
3. Simpan hasilnya dalam variabel `grouped_sex_bmi` dan tampilkan.

**Expected Output:**
```
Sex
0.0    27.107432
1.0    28.869696
Name: BMI, dtype: float64
```

In [ ]:
# Write your code here

### 11.b GroupBy dengan Beberapa Kolom dan Agregasi Gabungan

**Instruksi:**  
1. Gunakan `groupby()` untuk mengelompokkan data berdasarkan `Sex` dan `Smoker`.  
2. Gunakan `.agg()` untuk menghitung:
   - Rata-rata (`mean`) dari kolom `BMI`  
   - Jumlah (`sum`) dari kolom `Stroke`  
   - Jumlah baris (`count`) dari kolom `Age`  
3. Simpan hasilnya dalam variabel `grouped_multiagg` dan tampilkan.

**Expected Output:**
```
            BMI         Stroke Age
Sex Smoker                         
0.0 0.0     27.050351   18520  68500
    1.0     27.162215   21462  78472
1.0 0.0     28.572146    8383  27791
    1.0     29.111239    8993  29391
```

In [ ]:
# Write your code here

## Tugas 12: Transformasi Nilai dengan `.transform()`

### 12.a Menghitung Z-Score Kolom BMI per Grup `Sex`

**Instruksi:**  
1. Gunakan `groupby()` berdasarkan kolom `Sex`.  
2. Untuk tiap grup, hitung **z-score** dari kolom `BMI` menggunakan rumus:  
   \[(nilai - rata-rata grup) / standar deviasi grup\]  
3. Simpan hasilnya ke kolom baru bernama `BMI_zscore`.  
4. Tampilkan 5 baris pertama dari kolom `Sex`, `BMI`, dan `BMI_zscore`.

**Expected Output:**
```
   Sex   BMI   BMI_zscore
0  0.0  40.0     1.998579
1  0.0  25.0    -0.184745
2  0.0  28.0     0.073631
3  0.0  27.0    -0.012557
4  0.0  24.0    -0.270378
```

In [ ]:
# Write your code here

### 12.b Mengurangkan Rata-rata BMI per Grup `Sex`

**Instruksi:**  
1. Gunakan `groupby()` berdasarkan kolom `Sex`.  
2. Hitung rata-rata `BMI` untuk tiap grup dan kurangkan nilai BMI dengan rata-rata tersebut.  
3. Simpan hasilnya ke kolom baru bernama `BMI_centered`.  
4. Tampilkan 5 baris pertama dari kolom `Sex`, `BMI`, dan `BMI_centered`.

**Expected Output:**
```
   Sex   BMI    BMI_centered
0  0.0  40.0       12.892568
1  0.0  25.0       -2.107432
2  0.0  28.0        0.892568
3  0.0  27.0       -0.107432
4  0.0  24.0       -3.107432
```

In [ ]:
# Write your code here

## Tugas 13: Menggunakan `pivot_table()`

### 13.a Pivot Table: Rata-rata BMI Berdasarkan `Sex` dan `Smoker`

**Instruksi:**  
1. Buat pivot table dari dataset `df` untuk menghitung **rata-rata** (`mean`) `BMI`.  
2. Gunakan `Sex` sebagai index dan `Smoker` sebagai kolom pivot.  
3. Simpan hasilnya ke variabel `pivot_bmi` dan tampilkan.

**Expected Output:**
```
Smoker        0.0       1.0
Sex                          
0.0       27.050351  27.162215
1.0       28.572146  29.111239
```

In [ ]:
# Write your code here

### 13.b Pivot Table: Menampilkan Rata-rata dan Jumlah Stroke Berdasarkan `Sex` dan `Smoker`

**Instruksi:**  
1. Buat pivot table dengan `Sex` sebagai index dan `Smoker` sebagai kolom.  
2. Gunakan dua kolom nilai: `BMI` dan `Stroke`.  
3. Hitung **rata-rata (`mean`)** untuk `BMI` dan **jumlah (`sum`)** untuk `Stroke`.  
4. Simpan ke dalam variabel `pivot_multi` dan tampilkan.

**Expected Output:**
```
              BMI                  Stroke           
Smoker        0.0       1.0         0.0      1.0
Sex                                            
0.0       27.050351  27.162215   18520.0  21462.0
1.0       28.572146  29.111239    8383.0   8993.0
```

In [ ]:
# Write your code here

# Matplotlib

## 1. Line Plot (`plt.plot`)

**Instruksi:**  
1. Kelompokkan data berdasarkan kolom `Age` menggunakan `.groupby()`.  
2. Hitung rata-rata dari kolom `BMI` untuk tiap kelompok `Age`.  
3. Simpan hasil ke dalam `mean_bmi_by_age`.  
4. Buat line plot dengan sumbu X = `Age` dan sumbu Y = `BMI`.

**Expected Output:**
```
   Age        BMI
0  1.0  26.088070
1  2.0  27.606344
2  3.0  28.431538
...

(pada line plot)
```

In [ ]:
  # Write your code here

## 2. Bar Plot (`plt.bar`)

**Instruksi:**  
1. Filter data dengan kondisi `Diabetes_012 == 1.0`.  
2. Kelompokkan berdasarkan kolom `Income` dan hitung jumlah kemunculannya.  
3. Simpan hasilnya dalam `count_by_income`.  
4. Buat bar plot dari hasil tersebut.

**Expected Output:**
```
   Income  count
0     1.0    314
1     2.0    356
2     3.0    421
...

(pada bar plot)
```

In [ ]:
# Write your code here

## 3. Horizontal Bar Plot (`plt.barh`)

**Instruksi:**  
1. Kelompokkan data berdasarkan kolom `GenHlth`.  
2. Hitung rata-rata dari kolom `PhysHlth` untuk tiap kategori.  
3. Simpan hasilnya ke `avg_phys_by_gen`.  
4. Buat plot batang horizontal dari hasil tersebut.

**Expected Output:**
```
   GenHlth   PhysHlth
0      1.0   0.862602
1      2.0   1.532374
2      3.0   3.394257
...

(pada horizontal bar plot)
```

In [ ]:
# Write your code here

## 4. Pie Chart (`plt.pie`)

**Instruksi:**  
1. Gunakan `.value_counts()` untuk menghitung jumlah kategori pada kolom `Sex`.  
2. Simpan hasilnya ke `sex_counts`.  
3. Buat pie chart dari hasil tersebut.

**Expected Output:**
```
{0.0: 141974, 1.0: 111706}

(pada pie chart)
```

In [ ]:
# Write your code here

## 5. Stack Plot (`plt.stackplot`)

**Instruksi:**  
1. Kelompokkan data berdasarkan kolom `Age` menggunakan `.groupby()`.  
2. Hitung total `HighBP`, `HighChol`, dan `Stroke` untuk masing-masing `Age`.  
3. Ambil hanya 10 kelompok `Age` pertama.  
4. Simpan hasilnya ke `stack_data`.
4. Buat stack plot menggunakan `plt.stackplot()`.

**Expected Output:**
```
   Age  HighBP  HighChol  Stroke
0  1.0   492.0     502.0    21.0
1  2.0   881.0     953.0    29.0
...

(pada stack plot)
```

In [ ]:
# Write your code here

## 6. Histogram (`plt.hist`)

**Instruksi:**  
1. Ambil kolom `BMI` dan hapus nilai yang hilang (NaN) menggunakan `.dropna()`.  
2. Buat histogram dengan 30 bins.

**Expected Output:**
```
(distribusi nilai BMI pada histogram)
```

In [ ]:
# Write your code here

## 7. Scatter Plot (`plt.scatter`)

**Instruksi:**  
1. Ambil kolom `MentHlth` dan `PhysHlth`, lalu hapus baris yang mengandung `NaN`.  
2. Simpan pada `scatter_df`.
3. Buat scatter plot dengan sumbu X = `MentHlth`, Y = `PhysHlth`.

**Expected Output:**
```
   MentHlth  PhysHlth
0      18.0      15.0
1       0.0       0.0
2      30.0      30.0
...

(pada scatter plot)
```

In [ ]:
# Write your code here

## 8. Subplot (`plt.subplot`)

**Instruksi:**  
1. Buat 2 subplot secara vertikal.  
2. Subplot 1: Histogram `BMI`.  
3. Subplot 2: Histogram `Age`.

**Expected Output:**
```
(sebaran nilai BMI dan Age pada histogram pada subplot)
```

In [ ]:
# Write your code here

## 9. Subplots Grid (`plt.subplots`)

**Instruksi:**  
1. Buat layout grid 2x2 untuk 4 visualisasi berikut:  
   - Jumlah kategori `Diabetes_012` (bar plot)  
   - Histogram `BMI`  
   - Scatter plot `BMI` vs `Age`  
   - Pie chart `Sex`  
2. Gunakan `plt.subplots(2, 2)` untuk membuat layout.

**Expected Output:**
```
(keempat plot pada subplots grid 2x2)
```

In [ ]:
# Write your code here